#!/usr/bin/env python3
"""Writes the list of shell files and their content hash into site/sw.js.

    python3 tools/make_sw.py            rewrite the generated block
    python3 tools/make_sw.py --check    exit 1 if the block is out of date (used by a test and by CI)
    python3 tools/make_sw.py --site DIR work on another copy of the site (used by the update test)

Browsers only notice a new service worker when sw.js itself changes, so the hash of everything it caches has to be in
sw.js: change any shell file, run this, and the service worker changes with it. The cache is named after the hash.
What is cached is what the game needs to run offline; the social image, screenshots, robots.txt, sitemap and licence
texts are left out."""
import argparse
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
BEGIN = '/* --- generated by tools/make_sw.py: do not edit by hand'
END = '/* --- end generated'
LEFT_OUT_DIRS = {'screenshots'}
LEFT_OUT_FILES = {'sw.js', 'robots.txt', 'sitemap.xml', 'og.png'}
LEFT_OUT_SUFFIXES = {'.txt', '.md'}


def shell_files(site):
    files = []
    for path in sorted(site.rglob('*')):
        rel = path.relative_to(site)
        if not path.is_file() or path.name.startswith('.') or rel.parts[0] in LEFT_OUT_DIRS or rel.name in LEFT_OUT_FILES or path.suffix in LEFT_OUT_SUFFIXES:
            continue
        files.append(rel.as_posix())
    return files


def shell_hash(site, files):
    digest = hashlib.sha256()
    for rel in files:
        digest.update(rel.encode() + b'\0' + (site / rel).read_bytes() + b'\0')
    return digest.hexdigest()[:10]


def block(site):
    files = shell_files(site)
    listing = ['  \'./\','] + [f"  '{rel}'," for rel in files]
    return (f"{BEGIN} ------------------------------------------------------------- */\n"
            f"const SHELL_HASH = '{shell_hash(site, files)}';\n"
            "const SHELL = [\n" + '\n'.join(listing) + "\n];\n"
            f"{END} -------------------------------------------------------------------------------------------------- */")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--site', default=str(ROOT / 'site'))
    args = parser.parse_args()
    site = pathlib.Path(args.site)
    sw = site / 'sw.js'
    text = sw.read_text()
    pattern = re.compile(re.escape(BEGIN) + r'.*?' + re.escape(END) + r'[^\n]*', re.S)
    if len(pattern.findall(text)) != 1:
        print('sw.js has no single generated block', file=sys.stderr)
        return 2
    fresh = pattern.sub(lambda _: block(site), text)
    if args.check:
        if fresh != text:
            print('site/sw.js is out of date: run  python3 tools/make_sw.py', file=sys.stderr)
            return 1
        print('site/sw.js is up to date')
        return 0
    if fresh != text:
        sw.write_text(fresh)
    print(f'{sw}: {len(shell_files(site)) + 1} files, hash {shell_hash(site, shell_files(site))}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
